This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./FE 2 Report.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file FE 2 Report.acn....done (52 entries accepted, 0 rejected).
Sorting entries....done (322 comparisons).
Generating output file FE 2 Report.acr....done (42 lines written, 0 warnings).
Output written in FE 2 Report.acr.
Transcript written in FE 2 Report.alg.
